# coding: utf-8

"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.8.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from aries_cloudcontroller.apis.action_menu_api import router as ActionMenuApiRouter
from aries_cloudcontroller.apis.basicmessage_api import router as BasicmessageApiRouter
from aries_cloudcontroller.apis.connection_api import router as ConnectionApiRouter
from aries_cloudcontroller.apis.credential_definition_api import router as CredentialDefinitionApiRouter
from aries_cloudcontroller.apis.credentials_api import router as CredentialsApiRouter
from aries_cloudcontroller.apis.did_exchange_api import router as DidExchangeApiRouter
from aries_cloudcontroller.apis.discover_features_api import router as DiscoverFeaturesApiRouter
from aries_cloudcontroller.apis.discover_features_v20_api import router as DiscoverFeaturesV20ApiRouter
from aries_cloudcontroller.apis.endorse_transaction_api import router as EndorseTransactionApiRouter
from aries_cloudcontroller.apis.introduction_api import router as IntroductionApiRouter
from aries_cloudcontroller.apis.issue_credential_v10_api import router as IssueCredentialV10ApiRouter
from aries_cloudcontroller.apis.issue_credential_v20_api import router as IssueCredentialV20ApiRouter
from aries_cloudcontroller.apis.jsonld_api import router as JsonldApiRouter
from aries_cloudcontroller.apis.ledger_api import router as LedgerApiRouter
from aries_cloudcontroller.apis.mediation_api import router as MediationApiRouter
from aries_cloudcontroller.apis.multitenancy_api import router as MultitenancyApiRouter
from aries_cloudcontroller.apis.out_of_band_api import router as OutOfBandApiRouter
from aries_cloudcontroller.apis.present_proof_v10_api import router as PresentProofV10ApiRouter
from aries_cloudcontroller.apis.present_proof_v20_api import router as PresentProofV20ApiRouter
from aries_cloudcontroller.apis.resolver_api import router as ResolverApiRouter
from aries_cloudcontroller.apis.revocation_api import router as RevocationApiRouter
from aries_cloudcontroller.apis.schema_api import router as SchemaApiRouter
from aries_cloudcontroller.apis.server_api import router as ServerApiRouter
from aries_cloudcontroller.apis.trustping_api import router as TrustpingApiRouter
from aries_cloudcontroller.apis.wallet_api import router as WalletApiRouter

app = FastAPI(
    title="Aries Cloud Agent",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="v0.8.0",
)

app.include_router(ActionMenuApiRouter)
app.include_router(BasicmessageApiRouter)
app.include_router(ConnectionApiRouter)
app.include_router(CredentialDefinitionApiRouter)
app.include_router(CredentialsApiRouter)
app.include_router(DidExchangeApiRouter)
app.include_router(DiscoverFeaturesApiRouter)
app.include_router(DiscoverFeaturesV20ApiRouter)
app.include_router(EndorseTransactionApiRouter)
app.include_router(IntroductionApiRouter)
app.include_router(IssueCredentialV10ApiRouter)
app.include_router(IssueCredentialV20ApiRouter)
app.include_router(JsonldApiRouter)
app.include_router(LedgerApiRouter)
app.include_router(MediationApiRouter)
app.include_router(MultitenancyApiRouter)
app.include_router(OutOfBandApiRouter)
app.include_router(PresentProofV10ApiRouter)
app.include_router(PresentProofV20ApiRouter)
app.include_router(ResolverApiRouter)
app.include_router(RevocationApiRouter)
app.include_router(SchemaApiRouter)
app.include_router(ServerApiRouter)
app.include_router(TrustpingApiRouter)
app.include_router(WalletApiRouter)
