# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class MediationIdMatchInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MediationIdMatchInfo - a model defined in OpenAPI

        mediation_id: The mediation_id of this MediationIdMatchInfo [Optional].
    """

    mediation_id: Optional[str] = Field(alias="mediation_id", default=None)

MediationIdMatchInfo.update_forward_refs()
