# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ServiceDecorator(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceDecorator - a model defined in OpenAPI

        recipient_keys: The recipient_keys of this ServiceDecorator.
        routing_keys: The routing_keys of this ServiceDecorator [Optional].
        service_endpoint: The service_endpoint of this ServiceDecorator.
    """

    recipient_keys: List[str] = Field(alias="recipientKeys")
    routing_keys: Optional[List[str]] = Field(alias="routingKeys", default=None)
    service_endpoint: str = Field(alias="serviceEndpoint")

ServiceDecorator.update_forward_refs()
